// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Roller1;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 70);
    lv_obj_set_height(ui_Arc1, 72);
    lv_obj_set_x(ui_Arc1, -109);
    lv_obj_set_y(ui_Arc1, -64);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -54);
    lv_obj_set_y(ui_Slider1, 86);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 83);
    lv_obj_set_y(ui_Switch1, 65);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 4\nOption 5\nOption 6\nOption 7", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 2);
    lv_obj_set_y(ui_Roller1, -5);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Arc1 = NULL;
    ui_Slider1 = NULL;
    ui_Switch1 = NULL;
    ui_Roller1 = NULL;

}
